### PR TITLE
Fix: typo on sampleapi.html

### PR DESCRIPTION
**Pull request by diegoveloper**
Fixed a typo on `request` word.

Taking advantage of this PR, one question @steveseguin , how difficult is to add a new field on this form to insert an image link to use as avatar instead of using the Twitch -> account -> avatar.

Screenshot 2024-05-07 at 7 11 48 PM

Thanks for this great tool!

### CODE REVIEW

**Comment by steveseguin** [comment]
Thank you.

I pushed an update for you.  Specify `chatimg` with a URL in the data object, and it should no longer pull from Twitch the avatar image. It will use whatever is specified instead, if available.

**Comment by diegoveloper** [comment]
> Thank you.
> 
> I pushed an update for you. Specify `chatimg` with a URL in the data object, and it should no longer pull from Twitch the avatar image. It will use whatever is specified instead, if available.

Thanks @steveseguin , do we need an update on `sampleapi.html` ? or where we can send the chatimg?

**Comment by steveseguin** [comment]
image

does this help?


```
		var data = {};
		data.chatname = document.getElementById("namesenderfake").value;
	//	data.nameColor = "";
	//	data.chatbadges = "";
	//	data.backgroundColor = "";
	//	data.textColor = "";
		data.chatmessage =  document.getElementById("msgfake").value;
		data.chatimg = document.getElementById("avatarfake").value || ""; // will use Twitch API to get avatar is not specified
		data.hasDonation = document.getElementById("donationfake").value;
//		data.membership = "";
		data.type = "twitch"; // twitch.png gets used as the source icon, as a result

		post({"extContent":data, "apiid":WID}); 
		```

**Comment by diegoveloper** [comment]
yes 🙏🏽

**Pull request merged**
