### PR TITLE
fix twitch avatar when username != display name

### PR DESCRIPTION
**Pull request by as2648as**

### CODE REVIEW

**Comment by as2648as** [comment]
I have already fixed the issue.

**Comment by steveseguin** [comment]
Thank you for the pull request.

What exactly is  `.chat-author__intl-login` ?  I don't see it in my Twitch pop out, so I don't exactly know what this is doing or how to test it.

I'm not entirely sure I understand the problem, or why we would use data.displayName instead of just setting data.chatname with the correct name.  

Anyways, it doesn't seem like a problem, so I'll merge it for now.  Still love to get more details

**Comment by as2648as** [comment]
This is Twitch's [changelog](https://blog.twitch.tv/en/2016/08/22/localized-display-names-e00ee8d3250a/#.er1f4edsk), explaining the use of localized display names.
Most Twitch users in non-English speaking countries use this feature.

In the original twitch.js file, only username is used to retrieve a user's avatar.
When using "https://api.socialstream.ninja/twitch/?username=" + encodeURIComponent(chatname);,
display name is mistaken as chatname, causing the image to not respond.

The following image shows the twitch chat popout webpage after using localized display names:
twitch

**Comment by steveseguin** [comment]
Thank you, kindly. That helps me understand the purpose of it.

**Pull request merged**
